title: efemeridi
author: Lucilla Chasseur
email: your-email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  Materiali scolastici
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Lucilla Chasseur
  tagline: Materiali scolastici
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    #twitter: 
    #github:
    #linkedIn: in/jekyll
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll
    #scholar: zP8AvuYAAAAJ

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
  navigation:
    - title: HomePage
      url: "index"
    - title: "I A Bil"
      url: "/1a_bil"
      children:
        - title: "Filosofia/philosophie"
          url: "/1a_bil_filosofia"
        - title: "Storia/histoire"
          url: "/1a_bil_storia"
    - title: "II A Ord"
      url: "/2a_ord"
      children:
        - title: "Filosofia"
          url: "/2a_ord_filosofia"
        - title: "Storia"
          url: "/2a_ord_storia"
    - title: "4 C Art"
      url: "/4c_art"
      children:
        - title: "Filosofia"
          url: "/4c_art_filosofia"
    - title: "4 D Art"
      url: "/4d_art"
      children:
        - title: "Filosofia"
          url: "/4d_art_filosofia"
    - title: "5 D Art"
      url: "/5d_art"
      children:
        - title: "Filosofia"
          url: "/5d_art_filosofia"
   #- title: Blog
   #url: "/posts"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

# Build settings
#theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
